language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - jruby-19mode

gemfile:
  - test/Gemfile.test

services:
  - sqlite3

env:
  - RAILS_ENV=test

before_script:
  - cd test/dummy
  - rails generate userq:install

script:
  - rake test